apiVersion: v1
kind: Pod
metadata:
  generateName: model-training-
spec:
  restartPolicy: Never
  containers:
  - name: model-training
    image: alvaromrodrigues/mlflow-training:0.1.1
    imagePullPolicy: IfNotPresent
    env:
    - name: MLFLOW_TRACKING_URI
      value: http://172.30.88.96:5000/
    - name: MLFLOW_S3_ENDPOINT_URL
      value: http://172.30.154.254:9000/
    - name: AWS_ACCESS_KEY_ID
      value: "minioadmin"
    - name: AWS_SECRET_ACCESS_KEY
      value: "minioadmin"
    resources:
      requests:
        cpu: "500m"