apiVersion: v1
kind: Service
metadata:
  name: iris-model-service
spec:
  selector:
    app: iris-model
  ports:
  - protocol: "TCP"
    port: 8000
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model
spec:
  selector:
    matchLabels:
      app: iris-model
  replicas: 5
  template:
    metadata:
      labels:
        app: iris-model
    spec:
      containers:
      - name: iris-model
        image: alvaromrodrigues/mlflow-rest:0.1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: MLFLOW_RUN_ID
          value: 18f5561ca52e43f9b09ae8dd3b7ca2e0
        - name: MLFLOW_TRACKING_URI
          value: http://172.30.88.96:5000/
        - name: MLFLOW_S3_ENDPOINT_URL
          value: http://172.30.154.254:9000/
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        ports:
        - containerPort: 8000